<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21168" started-at="2019-12-18T22:17:17 EST" finished-at="2019-12-18T22:17:38 EST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21168" started-at="2019-12-18T22:17:17 EST" finished-at="2019-12-18T22:17:38 EST">
      <class name="com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1">
        <test-method status="PASS" signature="reportSetup()[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b]" name="reportSetup" is-config="true" duration-ms="213" started-at="2019-12-18T22:17:17 EST" finished-at="2019-12-18T22:17:17 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSetup -->
        <test-method status="PASS" signature="TestSetUp()[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b]" name="TestSetUp" is-config="true" duration-ms="11592" started-at="2019-12-18T22:17:17 EST" finished-at="2019-12-18T22:17:29 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSetUp -->
        <test-method status="PASS" signature="Test1()[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b]" name="Test1" duration-ms="11" started-at="2019-12-18T22:17:29 EST" finished-at="2019-12-18T22:17:29 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b]" name="getResult" is-config="true" duration-ms="736" started-at="2019-12-18T22:17:29 EST" finished-at="2019-12-18T22:17:29 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test1 status=SUCCESS method=TestCase1.Test1()[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TestSetUp()[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b]" name="TestSetUp" is-config="true" duration-ms="7241" started-at="2019-12-18T22:17:29 EST" finished-at="2019-12-18T22:17:37 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSetUp -->
        <test-method status="FAIL" signature="Test2()[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b]" name="Test2" duration-ms="4" started-at="2019-12-18T22:17:37 EST" finished-at="2019-12-18T22:17:37 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nnn] but found [sss]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nnn] but found [sss]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1.Test2(TestCase1.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b]" name="getResult" is-config="true" duration-ms="729" started-at="2019-12-18T22:17:37 EST" finished-at="2019-12-18T22:17:37 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test2 status=FAILURE method=TestCase1.Test2()[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1@3224f60b]" name="endReport" is-config="true" duration-ms="596" started-at="2019-12-18T22:17:37 EST" finished-at="2019-12-18T22:17:38 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.ipivot.InsuranceCalculator.DataDrivenTests.TestCase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
